export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

function Home({ children }) {
  return (
    <div className="pt-[100px] min-h-[650px] overflow-x-hidden">
      <div className="relative">{children}</div>
    </div>
  );
}

export default Home;
