import { Montserrat } from "next/font/google";
import "../styles/index.css";

const montserrat = Montserrat({
  subsets: ["latin"],
  weight: ["300", "400", "500", "600", "700", "800", "900"],
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="tr" className="html-content !p-0 no-scrollbar">
      <body className={`${montserrat.className} antialiased bg-zinc-50`}>
        {children}
      </body>
    </html>
  );
}
