import { Montserrat } from "next/font/google";
import "../styles/index.css";
import Navbar from "@/components/sections/Navbar";
import Footer from "@/components/sections/Footer";

const montserrat = Montserrat({
  subsets: ["latin"],
  weight: ["300", "400", "500", "600", "700", "800", "900"],
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="tr" className="html-content !p-0 no-scrollbar">
      <body className={`${montserrat.className} relative antialiased bg-white`}>
        <Navbar />
        <div className="pt-[100px] min-h-[650px]">
          <div
            aria-hidden="true"
            className="absolute inset-0 grid grid-cols-2 -space-x-52 opacity-40"
          >
            <div className="blur-[106px] h-56 bg-gradient-to-br from-purple-600 to-purple-400" />
            <div className="blur-[106px] h-32 bg-gradient-to-r from-cyan-400 to-sky-300" />
          </div>
          {children}
        </div>
        <Footer />
      </body>
    </html>
  );
}
